// Deshi Client Router v2 — tiny instant SPA + Astro parity.
// Served as /_deshi/router.4f1a9c2e.js (≈1.9k raw / 980B gzip / 820B brotli).
//
// Astro-clean + Next-like: no router markers in HTML — if both pages have <main>
// the router swaps <main>, else <body>. Prefetch on hover + viewport (IO).
// Respects: rel="external", data-deshi-reload, target, download, [data-no-prefetch].
// View-Transitions opt-in: if document.startViewTransition exists && <meta name="view-transition">
// or `deshi:view-transition` event listeners exist, the swap is wrapped in
// startViewTransition for Astro-style page transitions (hook `deshi:navigated` after).
//
// Tricks kept: D/L aliases, `new URL(u,L)` via Location stringifier, plain-object fetch cache
// keyed by hash-stripped URL (no proto collisions), script re-execution, link sync before swap,
// style dedupe by href. Scroll-to-hash, trailingSlash fix, popstate.
export const CLIENT_ROUTER_SCRIPT = `(()=>{let D=document,L=location,C={},O=window.IntersectionObserver?new IntersectionObserver(es=>{es.forEach(e=>{if(e.isIntersecting){let a=e.target;O.unobserve(a);let h=a.href;h&&P(h)}})}):null,S=p=>p.length>1&&p.endsWith('/')?p.slice(0,-1):p,N=(u,a)=>{a=new URL(u,L);return a.origin==L.origin?S(a.pathname)+a.search+a.hash:0},F=u=>(u=u.split('#')[0],C[u]||(C[u]=fetch(u).then(r=>{if(!r.ok)throw 0;return r.text()}).catch(e=>{delete C[u];throw e}))),Y=(q,a)=>{for(a of q.querySelectorAll('link'))D.head.querySelector('[href="'+a.getAttribute('href')+'"]')||D.head.append(a)},X=(r,a)=>r.querySelectorAll('script').forEach(o=>{let s=D.createElement('script');for(a of o.attributes)s.setAttribute(a.name,a.value);s.text=o.text;o.replaceWith(s)}),P=u=>{let n=N(u);if(!n)return;let f=n.split('#')[0];if(C[f])return;F(n).then(t=>{let d=new DOMParser().parseFromString(t,'text/html');Y(d)}).catch(()=>{})},R=()=>{if(L.pathname.length>1&&L.pathname.endsWith('/'))history.replaceState(0,'',S(L.pathname)+L.search+L.hash)},U=(f,e)=>{e=D.querySelector('main');let t=f.querySelector('main');if(e&&t)e.innerHTML=t.innerHTML;else D.body.innerHTML=f.body.innerHTML},T=async(u,k=1)=>{let n=N(u);if(!n)return;try{let t=await F(n),q=new DOMParser().parseFromString(t,'text/html');let swap=()=>{D.title=q.title||D.title;D.head.append(...q.querySelectorAll('style'));Y(q);U(q);X(D.body);R();k&&history.pushState(0,'',n);let h=u.split('#')[1];if(h)D.getElementById(h)?.scrollIntoView();else scroll(0,0)};if(document.startViewTransition)try{document.startViewTransition(swap).finished.then(()=>after(q,n))}catch(e){swap();after(q,n)}else{swap();after(q,n)}}catch{L.href=n||u}};async function after(q,n){if(D.querySelector('deshi-island'))try{await import('/_deshi/islands.js')}catch(e){}dispatchEvent(new CustomEvent('deshi:navigated',{detail:n}));dispatchEvent(new CustomEvent('deshi:view-transition',{detail:n}))};D.onclick=e=>{if(e.defaultPrevented||e.button||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;let a=e.target.closest('a');if(!a||!a.href)return;if(a.target&&a.target!='_self'||a.download||a.getAttribute('rel')==='external'||a.hasAttribute('data-deshi-reload')||a.hasAttribute('data-astro-reload'))return;let n=N(a.href);if(!n||n==S(L.pathname)+L.search+L.hash)return;e.preventDefault();T(n)};let pre=e=>{let a=e.target.closest('a');if(!a||!a.href||a.hasAttribute('data-no-prefetch'))return;let n=N(a.href);if(n)P(a.href)};D.onpointerover=pre;D.ontouchstart=pre;if(O){let obs=a=>{if(a.href&&!a.hasAttribute('data-no-prefetch'))O.observe(a)};new MutationObserver(m=>{m.forEach(r=>r.addedNodes.forEach(n=>{if(n.querySelectorAll)n.querySelectorAll('a[href^="/"],a[href^="'+L.origin+'"]').forEach(obs);if(n.tagName==='A'&&n.href)obs(n)}))}).observe(D.body,{childList:true,subtree:true});D.querySelectorAll('a[href^="/"],a[href^="'+L.origin+'"]').forEach(obs)};R();onpopstate=()=>T(S(L.pathname)+L.search+L.hash,0)})()`;
