// Deshi Client Router — tiny instant SPA navigation.
// Served as /_deshi/router.4f1a9c2e.js.
//
// Astro-clean + Next-like: no router markers in HTML — if both pages have <main>
// the router swaps <main>, else <body>. Prefetch on hover/touch.
// Respects: rel="external", data-deshi-reload, target, download, [data-no-prefetch].
//
// Tricks kept: D/L aliases, `new URL(u,L)` via Location stringifier, plain-object fetch cache
// keyed by hash-stripped URL (no proto collisions), script re-execution, link sync before swap,
// style dedupe by href. Scroll-to-hash, trailingSlash fix, popstate.
export const CLIENT_ROUTER_SCRIPT = `(()=>{let D=document,L=location,C={},S=p=>p.length>1&&p.endsWith('/')?p.slice(0,-1):p,N=(u,a)=>{a=new URL(u,L);return a.origin==L.origin?S(a.pathname)+a.search+a.hash:0},F=u=>(u=u.split('#')[0],C[u]||(C[u]=fetch(u).then(r=>{if(!r.ok)throw 0;return r.text()}).catch(e=>{delete C[u];throw e}))),Y=(q,a)=>{for(a of q.querySelectorAll('link'))D.head.querySelector('[href="'+a.getAttribute('href')+'"]')||D.head.append(a)},X=(r,a)=>r.querySelectorAll('script').forEach(o=>{let s=D.createElement('script');for(a of o.attributes)s.setAttribute(a.name,a.value);s.text=o.text;o.replaceWith(s)}),P=u=>{let n=N(u);if(!n)return;let f=n.split('#')[0];if(C[f])return;F(n).then(t=>{let d=new DOMParser().parseFromString(t,'text/html');Y(d)}).catch(()=>{})},R=()=>{if(L.pathname.length>1&&L.pathname.endsWith('/'))history.replaceState(0,'',S(L.pathname)+L.search+L.hash)},U=(f,e)=>{e=D.querySelector('main');let t=f.querySelector('main');if(e&&t)e.innerHTML=t.innerHTML;else D.body.innerHTML=f.body.innerHTML},T=async(u,k=1)=>{let n=N(u);if(!n)return;try{let t=await F(n),q=new DOMParser().parseFromString(t,'text/html');D.title=q.title||D.title;D.head.append(...q.querySelectorAll('style'));Y(q);U(q);X(D.body);R();k&&history.pushState(0,'',n);let h=u.split('#')[1];if(h)D.getElementById(h)?.scrollIntoView();else scroll(0,0);if(D.querySelector('deshi-island'))try{await import('/_deshi/islands.js')}catch(e){}dispatchEvent(new CustomEvent('deshi:navigated',{detail:n}))}catch{L.href=n||u}};D.onclick=e=>{if(e.defaultPrevented||e.button||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;let a=e.target.closest('a');if(!a||!a.href)return;if(a.target&&a.target!='_self'||a.download||a.getAttribute('rel')==='external'||a.hasAttribute('data-deshi-reload')||a.hasAttribute('data-astro-reload'))return;let n=N(a.href);if(!n||n==S(L.pathname)+L.search+L.hash)return;e.preventDefault();T(n)};let pre=e=>{let a=e.target.closest('a');if(!a||!a.href||a.hasAttribute('data-no-prefetch'))return;let n=N(a.href);if(n)P(a.href)};D.onpointerover=pre;D.ontouchstart=pre;R();onpopstate=()=>T(S(L.pathname)+L.search+L.hash,0)})()`;

